import type { FastifyInstance } from "fastify";

export function registerDocsRoutes(app: FastifyInstance): void {
  app.get("/api/docs", () => ({
    openapi: "3.1.0",
    info: {
      title: "MUNEEB.SYSTEMS GENERATOR API",
      version: app.appConfig.version,
      description:
        "Local-only Phase 6 generator management API with draft review, manual editing, staged content, preview sessions, and approval bundles. Do not expose publicly."
    },
    paths: Object.fromEntries(
      [
        "/health",
        "/ready",
        "/api/version",
        "/api/dashboard",
        "/api/content/status",
        "/api/content/{type}",
        "/api/settings",
        "/api/logs",
        "/api/github/status",
        "/api/github/rate-limit",
        "/api/github/repositories",
        "/api/github/repositories/{repositoryId}",
        "/api/github/sync",
        "/api/github/sync/full",
        "/api/github/sync/cancel",
        "/api/github/sync/status",
        "/api/github/selections/{repositoryId}",
        "/api/github/selections/bulk",
        "/api/github/repositories/{repositoryId}/notes",
        "/api/ai/runtime",
        "/api/ai/check",
        "/api/ai/start",
        "/api/ai/stop",
        "/api/ai/warm-up",
        "/api/ai/test-generation",
        "/api/queue",
        "/api/queue/enqueue",
        "/api/queue/start",
        "/api/queue/pause",
        "/api/queue/resume",
        "/api/queue/jobs/{jobId}/cancel",
        "/api/queue/jobs/{jobId}/retry",
        "/api/queue/retry-failed",
        "/api/drafts",
        "/api/drafts/{draftId}",
        "/api/reviews",
        "/api/reviews/{reviewId}",
        "/api/reviews/{reviewId}/working-copy",
        "/api/reviews/{reviewId}/revisions",
        "/api/reviews/{reviewId}/compare",
        "/api/reviews/{reviewId}/validate",
        "/api/reviews/{reviewId}/approve",
        "/api/reviews/{reviewId}/reject",
        "/api/reviews/{reviewId}/reopen",
        "/api/reviews/{reviewId}/mapping",
        "/api/staged",
        "/api/staged/status",
        "/api/staged/profile",
        "/api/staged/projects",
        "/api/staged/projects/{projectId}",
        "/api/staged/projects/{projectId}/hide",
        "/api/staged/projects/{projectId}/show",
        "/api/staged/projects/{projectId}/stage-delete",
        "/api/staged/experience",
        "/api/staged/experience/{entryId}",
        "/api/staged/skills",
        "/api/staged/activity",
        "/api/staged/activity/{entryId}",
        "/api/preview/sessions",
        "/api/preview/sessions/{sessionId}",
        "/api/preview/sessions/{sessionId}/data",
        "/api/publishing/status",
        "/api/publishing/bundles",
        "/api/publishing/bundles/{bundleId}",
        "/api/system",
        "/api/docs"
      ].map((apiPath) => [
        apiPath,
        { get: { description: "See shared Zod schemas for response contracts." } }
      ])
    )
  }));
}
