import type { Profile } from "@muneeb-systems/shared-types";
import { getContactLinks } from "@/lib/portfolio-selectors";

interface SiteFooterProps {
  profile: Profile;
}

export function SiteFooter({ profile }: SiteFooterProps) {
  return (
    <footer className="site-footer">
      <p>DESIGNED, ENGINEERED AND GENERATED BY MUNEEB ANJUM</p>
      <nav aria-label="Footer navigation">
        <a href="#top">Back to top</a>
        {getContactLinks(profile)
          .filter((link) => link.external)
          .map((link) => (
            <a key={link.href} href={link.href} rel="noreferrer" target="_blank">
              {link.label}
            </a>
          ))}
      </nav>
      <span>{new Date().getFullYear()} / PHASE 2</span>
    </footer>
  );
}
